### ISSUE TITLE
mixed-line-ending pre-commit hook

### ISSUE THREAD

**Issue by xbarra** [os-climate/devops-toolkit#206]
(Sadly) Some of our computers use Windows.

Since we use git for windows, we use the core.autocrlf option. 
> Git will convert LF to CRLF when checking out text files. When committing text files, CRLF will be converted to LF. For cross-platform projects, this is the recommended setting on Windows ("core.autocrlf" is set to "true").

When trying to run the pre-commit checks on a Windows machine, the `mixed-line-ending` pre-commit hook will change all line endings, creating a bit of a havoc. And this can result in some weird commits.

I understand that making the checks compatible with developers using windows is not a priority, but does someone know how could we handle this? 

[I mean other than when trying to run the pre-commit checks on a windows machine commenting this hook.]

**Comment by ModeSevenIndustrialSolutions** [comment]
Change merged.
